version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql-db
    container_name: mysql-db
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d